// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models.protobuf

package com.fathomdb.proxy.protobuf;

public final class ModelsProtobuf {
  private ModelsProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VfsItemModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional bytes hash = 2;
    boolean hasHash();
    com.google.protobuf.ByteString getHash();
    
    // optional uint64 length = 3;
    boolean hasLength();
    long getLength();
    
    // optional uint64 last_modified = 4;
    boolean hasLastModified();
    long getLastModified();
    
    // optional .VfsItemModel.WellKnownContentType well_known_content_type = 5;
    boolean hasWellKnownContentType();
    com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType getWellKnownContentType();
    
    // optional string content_type = 6;
    boolean hasContentType();
    String getContentType();
    
    // repeated .VfsItemModel child = 7;
    java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> 
        getChildList();
    com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel getChild(int index);
    int getChildCount();
    java.util.List<? extends com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder> 
        getChildOrBuilderList();
    com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder getChildOrBuilder(
        int index);
  }
  public static final class VfsItemModel extends
      com.google.protobuf.GeneratedMessage
      implements VfsItemModelOrBuilder {
    // Use VfsItemModel.newBuilder() to construct.
    private VfsItemModel(Builder builder) {
      super(builder);
    }
    private VfsItemModel(boolean noInit) {}
    
    private static final VfsItemModel defaultInstance;
    public static VfsItemModel getDefaultInstance() {
      return defaultInstance;
    }
    
    public VfsItemModel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fathomdb.proxy.protobuf.ModelsProtobuf.internal_static_VfsItemModel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fathomdb.proxy.protobuf.ModelsProtobuf.internal_static_VfsItemModel_fieldAccessorTable;
    }
    
    public enum WellKnownContentType
        implements com.google.protobuf.ProtocolMessageEnum {
      DIRECTORY(0, 0),
      ;
      
      public static final int DIRECTORY_VALUE = 0;
      
      
      public final int getNumber() { return value; }
      
      public static WellKnownContentType valueOf(int value) {
        switch (value) {
          case 0: return DIRECTORY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<WellKnownContentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<WellKnownContentType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WellKnownContentType>() {
              public WellKnownContentType findValueByNumber(int number) {
                return WellKnownContentType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final WellKnownContentType[] VALUES = {
        DIRECTORY, 
      };
      
      public static WellKnownContentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private WellKnownContentType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:VfsItemModel.WellKnownContentType)
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes hash = 2;
    public static final int HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString hash_;
    public boolean hasHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    
    // optional uint64 length = 3;
    public static final int LENGTH_FIELD_NUMBER = 3;
    private long length_;
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getLength() {
      return length_;
    }
    
    // optional uint64 last_modified = 4;
    public static final int LAST_MODIFIED_FIELD_NUMBER = 4;
    private long lastModified_;
    public boolean hasLastModified() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getLastModified() {
      return lastModified_;
    }
    
    // optional .VfsItemModel.WellKnownContentType well_known_content_type = 5;
    public static final int WELL_KNOWN_CONTENT_TYPE_FIELD_NUMBER = 5;
    private com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType wellKnownContentType_;
    public boolean hasWellKnownContentType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType getWellKnownContentType() {
      return wellKnownContentType_;
    }
    
    // optional string content_type = 6;
    public static final int CONTENT_TYPE_FIELD_NUMBER = 6;
    private java.lang.Object contentType_;
    public boolean hasContentType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getContentType() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          contentType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .VfsItemModel child = 7;
    public static final int CHILD_FIELD_NUMBER = 7;
    private java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> child_;
    public java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> getChildList() {
      return child_;
    }
    public java.util.List<? extends com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder> 
        getChildOrBuilderList() {
      return child_;
    }
    public int getChildCount() {
      return child_.size();
    }
    public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel getChild(int index) {
      return child_.get(index);
    }
    public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder getChildOrBuilder(
        int index) {
      return child_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      hash_ = com.google.protobuf.ByteString.EMPTY;
      length_ = 0L;
      lastModified_ = 0L;
      wellKnownContentType_ = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType.DIRECTORY;
      contentType_ = "";
      child_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, lastModified_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, wellKnownContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getContentTypeBytes());
      }
      for (int i = 0; i < child_.size(); i++) {
        output.writeMessage(7, child_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastModified_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, wellKnownContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContentTypeBytes());
      }
      for (int i = 0; i < child_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, child_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fathomdb.proxy.protobuf.ModelsProtobuf.internal_static_VfsItemModel_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fathomdb.proxy.protobuf.ModelsProtobuf.internal_static_VfsItemModel_fieldAccessorTable;
      }
      
      // Construct using com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChildFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastModified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        wellKnownContentType_ = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType.DIRECTORY;
        bitField0_ = (bitField0_ & ~0x00000010);
        contentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (childBuilder_ == null) {
          child_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          childBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDescriptor();
      }
      
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel getDefaultInstanceForType() {
        return com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDefaultInstance();
      }
      
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel build() {
        com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel buildPartial() {
        com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel result = new com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastModified_ = lastModified_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.wellKnownContentType_ = wellKnownContentType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.contentType_ = contentType_;
        if (childBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            child_ = java.util.Collections.unmodifiableList(child_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.child_ = child_;
        } else {
          result.child_ = childBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel) {
          return mergeFrom((com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel other) {
        if (other == com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasLastModified()) {
          setLastModified(other.getLastModified());
        }
        if (other.hasWellKnownContentType()) {
          setWellKnownContentType(other.getWellKnownContentType());
        }
        if (other.hasContentType()) {
          setContentType(other.getContentType());
        }
        if (childBuilder_ == null) {
          if (!other.child_.isEmpty()) {
            if (child_.isEmpty()) {
              child_ = other.child_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureChildIsMutable();
              child_.addAll(other.child_);
            }
            onChanged();
          }
        } else {
          if (!other.child_.isEmpty()) {
            if (childBuilder_.isEmpty()) {
              childBuilder_.dispose();
              childBuilder_ = null;
              child_ = other.child_;
              bitField0_ = (bitField0_ & ~0x00000040);
              childBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildFieldBuilder() : null;
            } else {
              childBuilder_.addAllMessages(other.child_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              hash_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              length_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastModified_ = input.readUInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType value = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                wellKnownContentType_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              contentType_ = input.readBytes();
              break;
            }
            case 58: {
              com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder subBuilder = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addChild(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional bytes hash = 2;
      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      
      // optional uint64 length = 3;
      private long length_ ;
      public boolean hasLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getLength() {
        return length_;
      }
      public Builder setLength(long value) {
        bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 last_modified = 4;
      private long lastModified_ ;
      public boolean hasLastModified() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getLastModified() {
        return lastModified_;
      }
      public Builder setLastModified(long value) {
        bitField0_ |= 0x00000008;
        lastModified_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastModified() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastModified_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .VfsItemModel.WellKnownContentType well_known_content_type = 5;
      private com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType wellKnownContentType_ = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType.DIRECTORY;
      public boolean hasWellKnownContentType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType getWellKnownContentType() {
        return wellKnownContentType_;
      }
      public Builder setWellKnownContentType(com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        wellKnownContentType_ = value;
        onChanged();
        return this;
      }
      public Builder clearWellKnownContentType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        wellKnownContentType_ = com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.WellKnownContentType.DIRECTORY;
        onChanged();
        return this;
      }
      
      // optional string content_type = 6;
      private java.lang.Object contentType_ = "";
      public boolean hasContentType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getContentType() {
        java.lang.Object ref = contentType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContentType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        contentType_ = value;
        onChanged();
        return this;
      }
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        contentType_ = getDefaultInstance().getContentType();
        onChanged();
        return this;
      }
      void setContentType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        contentType_ = value;
        onChanged();
      }
      
      // repeated .VfsItemModel child = 7;
      private java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> child_ =
        java.util.Collections.emptyList();
      private void ensureChildIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          child_ = new java.util.ArrayList<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel>(child_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder> childBuilder_;
      
      public java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> getChildList() {
        if (childBuilder_ == null) {
          return java.util.Collections.unmodifiableList(child_);
        } else {
          return childBuilder_.getMessageList();
        }
      }
      public int getChildCount() {
        if (childBuilder_ == null) {
          return child_.size();
        } else {
          return childBuilder_.getCount();
        }
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel getChild(int index) {
        if (childBuilder_ == null) {
          return child_.get(index);
        } else {
          return childBuilder_.getMessage(index);
        }
      }
      public Builder setChild(
          int index, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.set(index, value);
          onChanged();
        } else {
          childBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setChild(
          int index, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.set(index, builderForValue.build());
          onChanged();
        } else {
          childBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addChild(com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.add(value);
          onChanged();
        } else {
          childBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addChild(
          int index, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.add(index, value);
          onChanged();
        } else {
          childBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addChild(
          com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.add(builderForValue.build());
          onChanged();
        } else {
          childBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addChild(
          int index, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.add(index, builderForValue.build());
          onChanged();
        } else {
          childBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllChild(
          java.lang.Iterable<? extends com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel> values) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          super.addAll(values, child_);
          onChanged();
        } else {
          childBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearChild() {
        if (childBuilder_ == null) {
          child_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          childBuilder_.clear();
        }
        return this;
      }
      public Builder removeChild(int index) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.remove(index);
          onChanged();
        } else {
          childBuilder_.remove(index);
        }
        return this;
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder getChildBuilder(
          int index) {
        return getChildFieldBuilder().getBuilder(index);
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder getChildOrBuilder(
          int index) {
        if (childBuilder_ == null) {
          return child_.get(index);  } else {
          return childBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder> 
           getChildOrBuilderList() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(child_);
        }
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder addChildBuilder() {
        return getChildFieldBuilder().addBuilder(
            com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDefaultInstance());
      }
      public com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder addChildBuilder(
          int index) {
        return getChildFieldBuilder().addBuilder(
            index, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.getDefaultInstance());
      }
      public java.util.List<com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder> 
           getChildBuilderList() {
        return getChildFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder, com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModelOrBuilder>(
                  child_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:VfsItemModel)
    }
    
    static {
      defaultInstance = new VfsItemModel(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:VfsItemModel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VfsItemModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VfsItemModel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Models.protobuf\"\361\001\n\014VfsItemModel\022\014\n\004na" +
      "me\030\001 \001(\t\022\014\n\004hash\030\002 \001(\014\022\016\n\006length\030\003 \001(\004\022\025" +
      "\n\rlast_modified\030\004 \001(\004\022C\n\027well_known_cont" +
      "ent_type\030\005 \001(\0162\".VfsItemModel.WellKnownC" +
      "ontentType\022\024\n\014content_type\030\006 \001(\t\022\034\n\005chil" +
      "d\030\007 \003(\0132\r.VfsItemModel\"%\n\024WellKnownConte" +
      "ntType\022\r\n\tDIRECTORY\020\000B\035\n\033com.fathomdb.pr" +
      "oxy.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VfsItemModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VfsItemModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VfsItemModel_descriptor,
              new java.lang.String[] { "Name", "Hash", "Length", "LastModified", "WellKnownContentType", "ContentType", "Child", },
              com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.class,
              com.fathomdb.proxy.protobuf.ModelsProtobuf.VfsItemModel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
